# Site settings
email: martin2877@foxmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: MuheBlog
description: 木禾
url: "https://martin2877.github.io/"
twitter_username: 
default_img: 

# Profile settings
name: 木禾
profile_img: https://picsum.photos/470/300?image=1005
profile: Influence is Power.
social:
  github: https://github.com/Martin2877

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
